backup_to_json: true
convert_dates: true

restaurant: ""  

custom_url_base: https://mycustomurl.com
custom_url_profiles: /profiles/
custom_url_reviews: /reviews/

download_images: false
download_threads: 4
headless: false
image_dir: review_images

json_path: "data/reviews.json"
seen_ids_path: "data/reviews.ids"

mongodb:
  collection: google_reviews
  database: reviews
  uri: mongodb://localhost:27017

overwrite_existing: false
preserve_original_urls: true
replace_urls: false

sort_by: relevance
stop_on_match: false
store_local_paths: true

url: ""

use_mongodb: false