backup_to_json: true
convert_dates: true
restaurant: 24 - Le Restaurant
custom_url_base: https://mycustomurl.com
custom_url_profiles: /profiles/
custom_url_reviews: /reviews/
download_images: false
download_threads: 4
headless: false
image_dir: review_images
json_path: C:\Users\leemi\OneDrive\Documents\ENSAE\RA\Google reviews scraping\google-reviews-scraper-pro\data\24_le_restaurant\24_le_restaurant.json
seen_ids_path: C:\Users\leemi\OneDrive\Documents\ENSAE\RA\Google reviews scraping\google-reviews-scraper-pro\data\24_le_restaurant\24_le_restaurant.ids
mongodb:
  collection: google_reviews
  database: reviews
  uri: mongodb://localhost:27017
overwrite_existing: false
preserve_original_urls: true
replace_urls: false
sort_by: relevance
stop_on_match: false
store_local_paths: true
url: https://www.google.com/maps/place/?q=place_id:ChIJLe0K9sVv5kcRt9qr4CrfIZU&hl=en&gl=US
use_mongodb: false
