backup_to_json: true
convert_dates: true
custom_params:
  company: Simone
  source: Google Maps
  restaurant: L'Atelier de JoÃ«l Robuchon - St-Germain
custom_url_base: https://mycustomurl.com
custom_url_profiles: /profiles/
custom_url_reviews: /reviews/
download_images: false
download_threads: 4
headless: false
image_dir: review_images
json_path: C:\Users\leemi\OneDrive\Documents\ENSAE\RA\Google reviews scraping\google-reviews-scraper-pro\data\l_atelier_de_joel_robuchon_st_germain\l_atelier_de_joel_robuchon_st_germain.json
mongodb:
  collection: google_reviews
  database: reviews
  uri: mongodb://localhost:27017
overwrite_existing: false
preserve_original_urls: true
replace_urls: false
seen_ids_path: C:\Users\leemi\OneDrive\Documents\ENSAE\RA\Google reviews scraping\google-reviews-scraper-pro\data\l_atelier_de_joel_robuchon_st_germain\l_atelier_de_joel_robuchon_st_germain.ids
sort_by: relevance
stop_on_match: false
store_local_paths: true
url: https://www.google.com/maps/place/?q=place_id:ChIJU1Oe_ylu5kcRHk3j-D0X9ew
use_mongodb: false
