backup_to_json: true
convert_dates: true
restaurant: MoSuke
custom_url_base: https://mycustomurl.com
custom_url_profiles: /profiles/
custom_url_reviews: /reviews/
download_images: false
download_threads: 4
headless: false
image_dir: review_images
json_path: C:\Users\leemi\OneDrive\Documents\ENSAE\RA\Google reviews scraping\google-reviews-scraper-pro\data\mosuke\mosuke.json
seen_ids_path: C:\Users\leemi\OneDrive\Documents\ENSAE\RA\Google reviews scraping\google-reviews-scraper-pro\data\mosuke\mosuke.ids
mongodb:
  collection: google_reviews
  database: reviews
  uri: mongodb://localhost:27017
overwrite_existing: false
preserve_original_urls: true
replace_urls: false
sort_by: relevance
stop_on_match: false
store_local_paths: true
url: https://www.google.com/maps/place/?q=place_id:ChIJZf2wJx9x5kcRTD2DAPk3rP0&hl=en&gl=US
use_mongodb: false
